version: '3'

services:
  ovsdb:
    image: vdasari/erlango:latest
    container_name: ovsdb
    hostname: ovsdb
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    networks:
      default_ovsdb_net:
        ipv4_address: 10.1.123.10

  ovs1:
    image: vdasari/ovs:fst_debian_host
    container_name: ovs1
    hostname: ovs1
    command: start-userspace
    volumes:
        - ${HOME}:${HOME}
    networks:
      default_ovsdb_net:
        ipv4_address: 10.1.123.20

  ovs2:
    image: vdasari/ovs:fst_debian_host
    container_name: ovs2
    hostname: ovs2
    command: start-userspace
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    networks:
      default_ovsdb_net:
        ipv4_address: 10.1.123.30

networks:
  default_ovsdb_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.123.0/24
